/**
 * Multi-entry webpack configuration for Eightshift Multilang.
 *
 * Produces two independent bundles:
 *   build/settings/  — React settings page app
 *   build/editor/    — Gutenberg editor sidebar + translation modal
 *
 * Each bundle gets its own index.asset.php (generated by
 * @wordpress/dependency-extraction-webpack-plugin) which WordPress uses for
 * cache-busting and automatic script dependency resolution.
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path = require( 'path' );

const cwd = process.cwd();

/**
 * Merge the default config with per-bundle overrides.
 * We keep all loaders, plugins, and mode from the default config —
 * only the entry point and output path differ per bundle.
 *
 * @param {string} entry    Absolute path to the entry module.
 * @param {string} outDir   Output directory name relative to build/.
 */
function makeBundle( entry, outDir ) {
	return {
		...defaultConfig,
		entry: { index: entry },
		output: {
			...defaultConfig.output,
			path: path.resolve( cwd, 'build', outDir ),
		},
	};
}

module.exports = [
	makeBundle(
		path.resolve( cwd, 'src/scripts/settings/index.js' ),
		'settings',
	),
	makeBundle(
		path.resolve( cwd, 'src/scripts/editor/index.js' ),
		'editor',
	),
];
