<?php

declare(strict_types=1);

namespace EightshiftMultilang\Admin;

use EightshiftMultilang\Languages\LanguageRepository;

/**
 * Registers the plugin settings page in the WordPress admin.
 *
 * The page itself renders a React mount point (<div id="esml-settings-root">).
 * The React application (built in Sprint 5) is enqueued here and mounts into
 * that element. The page therefore has no server-rendered form fields — all
 * settings interaction goes through the REST API.
 *
 * Admin page slug: eightshift-multilang
 * Menu position: top-level (between Comments and Appearance)
 */
final class SettingsPage
{
	/** Handle used for both the JS and CSS assets. */
	private const ASSET_HANDLE = 'esml-settings';

	/** Option page slug — matches the value used in PluginActivation redirect. */
	public const PAGE_SLUG = 'eightshift-multilang';

	/**
	 * WordPress admin screen ID for this top-level page.
	 * Hook suffix for add_menu_page() is 'toplevel_page_{slug}'.
	 */
	public const SCREEN_ID = 'toplevel_page_eightshift-multilang';

	public function __construct(
		private readonly LanguageRepository $languageRepository,
	) {
	}

	public function register(): void
	{
		add_action('admin_menu', [$this, 'registerMenu']);
		add_action('admin_enqueue_scripts', [$this, 'enqueueAssets']);
	}

	/**
	 * Register the top-level Multilang menu page.
	 *
	 * Positioned at 30 — after Comments (25) and before Appearance (60),
	 * reflecting that it's a core content-management tool when active.
	 */
	public function registerMenu(): void
	{
		add_menu_page(
			__('Eightshift Multilang', 'eightshift-multilang'),
			__('Multilang', 'eightshift-multilang'),
			'manage_options',
			self::PAGE_SLUG,
			[$this, 'render'],
			'dashicons-translation',
			30,
		);
	}

	/**
	 * Enqueue the compiled React app on the plugin's settings page only.
	 *
	 * The asset file (build/settings/index.asset.php) is generated by
	 * @wordpress/scripts and contains auto-detected dependencies and a
	 * cache-busting version hash.
	 *
	 * @param string $hookSuffix Current admin page hook suffix.
	 */
	public function enqueueAssets(string $hookSuffix): void
	{
		if ($hookSuffix !== self::SCREEN_ID) {
			return;
		}

		$assetFile = ESML_PLUGIN_DIR . 'build/settings/index.asset.php';

		// Asset file is only present after `npm run build`; skip gracefully in
		// development before the first build.
		if (! file_exists($assetFile)) {
			return;
		}

		/** @var array{dependencies: string[], version: string} $asset */
		$asset = require $assetFile;

		wp_enqueue_script(
			self::ASSET_HANDLE,
			ESML_PLUGIN_URL . 'build/settings/index.js',
			$asset['dependencies'],
			$asset['version'],
			true,
		);

		$styleFile = ESML_PLUGIN_DIR . 'build/settings/style-index.css';

		if (file_exists($styleFile)) {
			wp_enqueue_style(
				self::ASSET_HANDLE,
				ESML_PLUGIN_URL . 'build/settings/style-index.css',
				[],
				$asset['version'],
			);
		}

		// Pass data the React app needs before its first REST call.
		wp_localize_script(self::ASSET_HANDLE, 'esmSettings', $this->scriptData());
	}

	/**
	 * Render the settings page shell.
	 * The React app mounts into #esml-settings-root.
	 */
	public function render(): void
	{
		if (! current_user_can('manage_options')) {
			wp_die(esc_html__('You do not have sufficient permissions to access this page.', 'eightshift-multilang'));
		}

		echo '<div class="wrap">';
		echo '<div id="esml-settings-root"></div>';
		echo '</div>';
	}

	// ---------------------------------------------------------------------------
	// Internals
	// ---------------------------------------------------------------------------

	/**
	 * Data passed via wp_localize_script — available as window.esmSettings.
	 *
	 * @return array<string, mixed>
	 */
	private function scriptData(): array
	{
		return [
			'restUrl'   => esc_url_raw(rest_url('eightshift-multilang/v1')),
			'nonce'     => wp_create_nonce('wp_rest'),
			'pluginUrl' => ESML_PLUGIN_URL,
			'version'   => ESML_PLUGIN_VERSION,
			'i18n'      => [
				'pageTitle'   => __('Eightshift Multilang Settings', 'eightshift-multilang'),
				'saveSuccess' => __('Settings saved.', 'eightshift-multilang'),
				'saveError'   => __('Failed to save settings.', 'eightshift-multilang'),
			],
		];
	}
}
